       <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            DataTables Advanced Tables
                            <p><a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'add'));?>">Add new album</a></p>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                            	
                                <thead>
                                    <tr>
                                        <th>Autori</th>
                                        <th>Titulli</th>
                                        <th>Edit</th>
                                        <th> Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                              <?php
                              var_dump($this->paginator);
							
                                	foreach($this->paginator as $album)
    {

?>
  
       
                                    <tr class="odd gradeX">
                                        <td><?php  echo $album['artist'];?></td>
                                         <td><?php echo $album['title']; ?></td>
                                        

                                    </tr>
                                    <?php
                                     
                                      }
	echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml')
?>
                                   
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                       
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

