<?php echo $this->paginationControl($this->paginator, 'Elastic', 'controls.phtml'); 
foreach($this->paginator as $record)
    {
        echo $record['title'];
    }
?>
      
 <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>accno</th>
                                        <th>issbn</th>
                                        <th>title</th>
                                        <th>author</th>
                                        <th>publisher</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="odd gradeX">
                                        <td>Trident</td>
                                        <td>Internet Explorer 4.0</td>
                                        <td>Win 95+</td>
                                        <td class="center">4</td>
                                        <td class="center">X</td>
                                    </tr>
                                 
                                </tbody>
                            </table>